### ISSUE TITLE
Failure due to node version (expect 16)

### ISSUE THREAD

**Issue by brianjcolombini** [actions-hub/stylelint#13]
Similar issue to #10, #9, and #4 

`error grunt@1.6.1: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.18.1"`

Does the base image need to be updated?

**Comment by tsiatka** [comment]
same issue here

**Comment by joe-stubbs** [comment]
Same issue here....

**Comment by jon48** [comment]
Same issue, conflicting with `postcss-image-inliner@7.0.1`

**Comment by bootstrapdisruptive** [comment]
Same here. Using it in a github pipeline, calling stylelint getting a 14.18.1 error with another module

`
... 
  lintCSS:
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ needs.changes.outputs.css == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      # install dependencies
      - name: Install dependencies
        run: npm ci      
      # run CSS Linter
      - name: CSS Linter (stylelint)
        uses: actions-hub/stylelint@master
        env:
          PATTERN: "App/gfx/*.css"`
...`

Errors with 
error jest-location-mock@2.0.0: The engine "node" is incompatible with this module. Expected version "^16.10.0 || >=18.0.0". Got "14.18.1"
error Found incompatible module.

**Comment by nhatthm** [comment]
Hi folks, can you test this fork https://github.com/nhatthm/stylelint

```yaml
name: Test
on: [push]

jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: nhatthm/stylelint@master
```
