### ISSUE TITLE
Failing on repo with node 12

### ISSUE THREAD

**Issue by lstrzebinczyk** [actions-hub/stylelint#4]
Hello

I'm trying to use this action in my repo with these steps in `ci.yml` :

```
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn install
    - name: stylelint
      uses: actions-hub/stylelint@master
```

Additionally, in my package.json:

```
  "engines": {
    "node": "12.*"
  }
```

And I receive the following error in github actions:

```
error web@0.0.0: The engine "node" is incompatible with this module. Expected version "12.*". Got "10.19.0"
error Found incompatible module.
```

I'm fairly new to github actions, is that an issue with this repo, or should I fix it in my own repo? We expect our code to run only on node 12, and there are no other issues anywhere else with that requirement.
